#
# Makefile for muic devices
#
subdir-ccflags-y := -Wformat
obj-y += muic_manager.o
obj-y += common_muic.o
common_muic-y   := muic_notifier.o muic_param.o
common_muic-y += muic_sysfs.o
common_muic-y += muic_core.o

